// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADt9h0r8XB1VFvhpkfCcW41Fz7GFfjrPk',
    appId: '1:859661221744:web:8a7e87d64c4def076b19b5',
    messagingSenderId: '859661221744',
    projectId: 'thietbibaochay-v2',
    authDomain: 'thietbibaochay-v2.firebaseapp.com',
    databaseURL: 'https://thietbibaochay-v2-default-rtdb.firebaseio.com',
    storageBucket: 'thietbibaochay-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDznTGBbYNQJ7xdgwdLbr6mnQFlbq0ukLg',
    appId: '1:859661221744:android:babfeeb6242d14b36b19b5',
    messagingSenderId: '859661221744',
    projectId: 'thietbibaochay-v2',
    databaseURL: 'https://thietbibaochay-v2-default-rtdb.firebaseio.com',
    storageBucket: 'thietbibaochay-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCphe44756X4M0IRQhj2u20Knd6wGECL9I',
    appId: '1:859661221744:ios:17d25fd9f3bc08de6b19b5',
    messagingSenderId: '859661221744',
    projectId: 'thietbibaochay-v2',
    databaseURL: 'https://thietbibaochay-v2-default-rtdb.firebaseio.com',
    storageBucket: 'thietbibaochay-v2.appspot.com',
    iosBundleId: 'com.example.fireAlarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCphe44756X4M0IRQhj2u20Knd6wGECL9I',
    appId: '1:859661221744:ios:1075be3fa560b7716b19b5',
    messagingSenderId: '859661221744',
    projectId: 'thietbibaochay-v2',
    databaseURL: 'https://thietbibaochay-v2-default-rtdb.firebaseio.com',
    storageBucket: 'thietbibaochay-v2.appspot.com',
    iosBundleId: 'com.example.fireAlarmApp.RunnerTests',
  );
}
